Write-Host "QuickDrop local dev demo"
Write-Host ""
Write-Host "Manual Windows PowerShell terminals:"
Write-Host "  Terminal 1: go run ./cmd/quickdrop init-dev"
Write-Host "  Terminal 1: go run ./cmd/quickdrop hub -c configs/dev/hub.json"
Write-Host "  Terminal 2: go run ./cmd/quickdrop agent -c configs/dev/laptop.json"
Write-Host "  Terminal 3: go run ./cmd/quickdrop agent -c configs/dev/workstation.json"
Write-Host "  Terminal 4: go run ./cmd/quickdrop text -c configs/dev/laptop.json device:workstation `"hello from laptop`""
Write-Host "  Terminal 4: go run ./cmd/quickdrop send -c configs/dev/laptop.json device:workstation README.md"
Write-Host "  Terminal 4: go run ./cmd/quickdrop text -c configs/dev/laptop.json group:all `"hello all`""
Write-Host "  Terminal 5: go run ./cmd/quickdrop gui -c configs/dev/laptop.json"
Write-Host ""
Write-Host "Start-Process examples:"
Write-Host "  Start-Process powershell -ArgumentList '-NoExit','-Command','go run ./cmd/quickdrop hub -c configs/dev/hub.json'"
Write-Host "  Start-Process powershell -ArgumentList '-NoExit','-Command','go run ./cmd/quickdrop agent -c configs/dev/laptop.json'"
Write-Host "  Start-Process powershell -ArgumentList '-NoExit','-Command','go run ./cmd/quickdrop agent -c configs/dev/workstation.json'"
